### PR TITLE
Fix a bug in Camembert embeddings

### PR DESCRIPTION
**Pull request by Alea4jacta6est**

### CODE REVIEW

**Comment by alanakbik** [comment]
Thanks! Does this error only occur if you use Camembert embeddings in a StackedEmbedding?

**Comment by Alea4jacta6est** [comment]
No, I didn't use StackedEmbeddings,  my code: 
embeddings = CamembertEmbeddings()
tagger = SequenceTagger(
    hidden_size=256,
    embeddings=embeddings,
    tag_dictionary=tag_dictionary,
    tag_type=tag_type,
    use_crf=True,
    use_rnn=True,
    beta=0.5
)

**Comment by alanakbik** [comment]
Ah I see! Could you modify the IF part such that it fires with any number in the beginning? So for '1-camembert', '2-camembert' etc?

**Comment by Alea4jacta6est** [comment]
Yes, sure
This bug is also mentioned here https://github.com/flairNLP/flair/issues/1422

**Comment by alanakbik** [comment]
Great, thanks for fixing this!

**Pull request merged**
