### PR TITLE
allow BIO evaulation on sequence tagger

### PR DESCRIPTION
**Pull request by helpmefindaname**
fixes https://github.com/flairNLP/flair/issues/2784

### CODE REVIEW

**Comment by alanakbik** [comment]
Thanks for fixing this @helpmefindaname! 

@susannaruecker can you review this PR?

**Review by susannaruecker — APPROVED** [review]
Thank you for fixing this @helpmefindaname!

I could reproduce the bug described in #2784 which was indeed coming from the missing BIO formatting in `_get_gold_labels`. With your changes, now the gold label formatting as well as training and evaluating works fine, as tested on both BIO and BIOES format.

**Comment by bashayerm** [comment]
The problem doesn't solve for me, and I still get the same error 

error

**Comment by helpmefindaname** [comment]
hi @bashayerm 
can you please add the full error message and a minimal example that keeps failing?

**Comment by alanakbik** [comment]
@bashayerm this is only fixed in the master branch. If you installed through pip you don't yet have this change. You need to test with current master branch to see if the error is fixed.

**Comment by helpmefindaname** [comment]
Hey @alanakbik as @bashayerm isn't responding any more and the PR is already approved, can we merge this bug fix?

**Comment by alanakbik** [comment]
@helpmefindaname thanks for the bump, yes let's merge! Sorry for the long delays in merging PRs at the moment - this will improve in a few weeks (lots of deadlines until then)!

**Pull request merged**
