### PR TITLE
set whitespace_after in UniversalDependenciesDataset

### PR DESCRIPTION
**Pull request by djstrong**
Set `whitespace_after` in `UniversalDependenciesDataset`, so `to_plain_string` method is returning original sentence.

### CODE REVIEW

**Comment by alanakbik** [comment]
(closed and reopened to re-trigger Travis build)

**Comment by alanakbik** [comment]
@djstrong thanks for adding this!

**Comment by alanakbik** [comment]
:+1:

**Comment by djstrong** [comment]
Is this indentation intentional? It is not consistent with other files.

**Comment by alanakbik** [comment]
I removed the black formatting requirement from travis in the hope that this would make contributions easier. But then stuff like this can happen, so maybe it's better to put black formatting requirement back in?

**Comment by djstrong** [comment]
Thank you for correcting also for online iteration.

**Pull request merged**
