### PR TITLE
Memory leak word embeddings

### PR DESCRIPTION
**Pull request by whoisjones**
functools lru_cache doesn't follow self object's lifetime, thus the memory leak. replaced with methodtools.
closes GH-2013.

### CODE REVIEW

**Comment by alanakbik** [comment]
@whoisjones thanks for adding this!

**Comment by Michael95-m** [comment]
@whoisjones ,did this update affect and fix memory leak  in trained sequence tagger models. In my case, when I deployed flair models with flask and uwsgi, memory increases with time. But I'm not very sure this is because of the flair model but I highly suspects this.

**Comment by alanakbik** [comment]
Are you running this from master branch? The update was pushed after the last Flair release so if you install from pip you don't yet have it.

**Comment by Michael95-m** [comment]
@alanakbik , can I install with ` pip install git+https://github.com/flairNLP/flair.git`  to get this fix??

**Comment by alanakbik** [comment]
Yes that would work!

**Pull request merged**
