### PR TITLE
Add stalebot to Flair

### PR DESCRIPTION
**Pull request by alanakbik**
This PR adds config for stalebot to automatically close issues with long periods of inactivity. In the first phase, issues need to be inactive for 120 days before they get closed. This may be shortened in the future when our release cycles become more frequent.

### CODE REVIEW

**Comment by alanakbik** [comment]
:+1:

**Comment by alanakbik** [comment]
@stefan-it can you also give a :+1:? then we can also check if zappr works.

**Comment by stefan-it** [comment]
:+1:

**Comment by stefan-it** [comment]
:heart: 

image

**Pull request merged**
