### PR TITLE
GH-538: attention

### PR DESCRIPTION
**Pull request by alanakbik**
This PR adds a layer of attention implemented by @53X to the `TextClassifier`. 

You can activate it by setting `attention=True` in the `TextClassifier` initialization.

### CODE REVIEW

**Comment by alanakbik** [comment]
:+1:

**Comment by alanakbik** [comment]
@MichaelHintz @stefan-it @kashif could you check, +1 and merge?

**Comment by 53X** [comment]
Hi, @alanakbik  @stefan-it  @kashif @MichaelHintz can this be merged? I am actually planning to use it in one of my problems

**Comment by kashif** [comment]
@53X I fixed the conflict, is it possible to add a test?

**Comment by 53X** [comment]
@kashif , can you please elaborate on the kind of test?

**Comment by 53X** [comment]
@alanakbik , there is a bug in this code .

**Comment by alanakbik** [comment]
@53X what is the bug?

**Comment by 53X** [comment]
While loading back the model, if we forget to pass the bidirectional parameter's value, then only it gives an error for bidirectional cases. Otherwise it's fine. Adding that solves the issue. See **load_from_file** function in text_classifcation_model.py

**Comment by loopdigga98** [comment]
Are you planning to add attention to NER classifier?

**Comment by alanakbik** [comment]
@loopdigga98 that's a good idea. We are currently refactoring the model interfaces and classes so adding attention as an optional layer in all tasks could be interesting!

**Comment by stefan-it** [comment]
One question: could the newly introduced [MultiheadAttention](https://github.com/pytorch/pytorch/pull/18334) class be used here 🤔 It is available in PyTorch 1.1.0 :)

**Comment by alanakbik** [comment]
Oh looks interesting! Might be worth a try :)

**Comment by aptperson** [comment]
Is this still going to be merged?

**Comment by djstrong** [comment]
Here are perplexities that can be achieved by adding single head attention to LSTM: https://github.com/Smerity/sha-rnn

**Comment by lfdharo** [comment]
Hello everyone, is it possible to get the attention weights that the TextClassifier is assigning to each word/token in the sentence to provide the final score in a multiclass setup? I thought that this was the spirit of the proposed incorporation to the library, but it seems it is not currently available in the latest version.

**Pull request closed without merging**
