### PR TITLE
Entity linking

### PR DESCRIPTION
**Pull request by marcelmmm**
EntityLinker and Entity Linking Datasets

### CODE REVIEW

**Comment by alanakbik** [comment]
I think the dependency 'wikipediaapi' needs to be added to requirements.txt

**Comment by alanakbik** [comment]
I've added the missing requirements and also changed the default sentence splitters to Sektok since SpaCy requires additional modules to be installed that don't come with default Flair. In the `AQUAINT_EL` and `IITB_EL` corpora, you can now pass the `sentence_splitter` as an argument in case you want to use SpaCy instead.

However, unfortunately the change to SegTok broke `AQUAINT_EL` since it now sometimes splits a sentence at the wrong place and breaks up an entity. You can reproduce this error with: 

```python
corpus = AQUAINT_EL()
```

Could you take a look?

**Comment by marcelmmm** [comment]
Thank you for all this!!
I changed the AQUAINT_EL corpus. Now it works when using SegTok as well.

**Comment by alanakbik** [comment]
@marcelmmm thanks a lot for adding this!

**Pull request merged**
