### PR TITLE
forward lang ids in TransformerWordEmbeddings

### PR DESCRIPTION
**Pull request by helpmefindaname**
closes https://github.com/flairNLP/flair/issues/2416

### CODE REVIEW

**Comment by helpmefindaname** [comment]
I noticed, that in the rebasing, it was implemented that multiple sentences get embedded at once. As the language id is only 
calculated for the first sentence, this might lead to downsides while embedding multiple sentences of different languages
-> The PR is set to draft until I fixed that

**Comment by alanakbik** [comment]
Hello @helpmefindaname thanks for the PR! I did not know that some transformers require language IDs to improve embeddings. Is there documentation on this somewhere, bzw a list of all transformer models that use language IDs?

**Comment by helpmefindaname** [comment]
Hey @alanakbik sure, here is the documentation: https://huggingface.co/transformers/multilingual.html#xlm-language-embeddings
it is basically a feature of XLM, there are also more models based on XLM that benefit from it, in my case it is https://huggingface.co/microsoft/unihanlm-base

**Comment by alanakbik** [comment]
@helpmefindaname thanks for adding this!

**Pull request merged**
