### PR TITLE
IGBO_NER addition to FlairNLP

### PR DESCRIPTION
**Pull request by PhilippThamm**
Added the corpus IGBO_NER for named entity recognition in the language Igbo to the flair framework.

### CODE REVIEW

**Comment by alanakbik** [comment]
@PhilippThamm I am getting some weird results when I load this dataset: 

```python
corpus = IGBO_NER()

# print statistics
print(corpus)

# print some example sentences
print(corpus.train[0])
print(corpus.train[0])
print(corpus.train[1])
print(corpus.train[2])
print(corpus.train[3])

# print the NER dictionary (should be only NER tags like B-PER, I-PER, E-PER, B-ORG, I-ORG)
corpus.make_label_dictionary('ner')
```

This prints a lot of weird characters. Perhaps the encoding is wrongly set?

**Review by alanakbik — CHANGES_REQUESTED** [review]
Fix encoding and set tag_to_bioes variable

**Comment by Dabendorf** [comment]
> @PhilippThamm I am getting some weird results when I load this dataset:
> 
> ```python
> corpus = IGBO_NER()
> 
> # print statistics
> print(corpus)
> 
> # print some example sentences
> print(corpus.train[0])
> print(corpus.train[0])
> print(corpus.train[1])
> print(corpus.train[2])
> print(corpus.train[3])
> 
> # print the NER dictionary (should be only NER tags like B-PER, I-PER, E-PER, B-ORG, I-ORG)
> corpus.make_label_dictionary('ner')
> ```
> 
> This prints a lot of weird characters. Perhaps the encoding is wrongly set?

As I understand it, the encoding should be set to utf-8 instead of Latin-1

**Comment by alanakbik** [comment]
@PhilippThamm thanks for adding this!

**Pull request merged**
