### PR TITLE
remove konoha from requirements.txt

### PR DESCRIPTION
**Pull request by marctorsoc**

### CODE REVIEW

**Comment by alanakbik** [comment]
Hello @marctorsoc, thanks for the PR! The tests are failing since we test for Japanese tokenization. That test would need to be removed. You should also run black formatting (see [here](https://github.com/flairNLP/flair/blob/master/CONTRIBUTING.md#code-formatting)) to pass the checks.

**Comment by marctorsoc** [comment]
@alanakbik this should be fixed now, I think

**Comment by alanakbik** [comment]
@marctorsoc thanks for fixing this!

**Comment by marctorsoc** [comment]
> @marctorsoc thanks for fixing this!

For what I see in https://github.com/flairNLP/flair/blob/master/.github/workflows/ci.yml, there's no automatic release. Could you release a new version after this? Do you plan to add auto-release when a PR is merged to master, or you prefer to keep manual like now?

**Comment by alanakbik** [comment]
We'll try to release a new version soon, and after that switch to more frequent updates!

**Pull request merged**
