### PR TITLE
Adding afrikaans support to flair nlp project

### PR DESCRIPTION
**Pull request by QueStat**
This is my solution for the current "Semester Projekt Gruppe 5" task.

Kind regards
Martin Vogel

### CODE REVIEW

**Review by alanakbik — CHANGES_REQUESTED** [review]
The code throws errors when I load the object: 

```python
# load corpus (throws error)
corpus = UD_AFRIKAANS()

# print corpus
print(corpus)

# print some sentences in corpus
print(corpus.train[1])
print(corpus.dev[1])
print(corpus.test[1])

# print UPOS tags
dictionary = corpus.make_tag_dictionary('upos')
print(dictionary)
```

Can you double-check?

**Comment by QueStat** [comment]
> The code throws errors when I load the object:
> 
> ```python
> # load corpus (throws error)
> corpus = UD_AFRIKAANS()
> 
> # print corpus
> print(corpus)
> 
> # print some sentences in corpus
> print(corpus.train[1])
> print(corpus.dev[1])
> print(corpus.test[1])
> 
> # print UPOS tags
> dictionary = corpus.make_tag_dictionary('upos')
> print(dictionary)
> ```
> 
> Can you double-check?

Fixed now?

Kind regards
Martin Vogel

**Comment by alanakbik** [comment]
Does this code run for you locally?

**Comment by QueStat** [comment]
> Does this code run for you locally?

Now it does. I have sent a e-mail to you with the logs :)

Kind regards
Martin Vogel

**Review by alanakbik — APPROVED** [review]

**Comment by alanakbik** [comment]
@QueStat great, thanks for adding this!

**Pull request merged**
