### PR TITLE
add prediction label type for span classifier

### PR DESCRIPTION
**Pull request by helpmefindaname**

### CODE REVIEW

**Review by alanakbik — COMMENTED** [review]
This currently does not work. To reproduce: 

```python
from flair.data import Sentence
from flair.models import MultitaskModel

# For comparison: This works since the label type is "ner" for both models in the multitask model
classifier: MultitaskModel = MultitaskModel.load("zelda")

sentence = Sentence("Kirk and Spock met on the Enterprise")

classifier.predict(sentence)

print(sentence)

# Giving them sensible label names, now made possible with this PR
classifier.tasks["Task_1"]._label_type = "nel"
classifier.tasks["Task_1"]._span_label_type = "ner"

# However, this no longer makes predictions
sentence = Sentence("Kirk and Spock met on the Enterprise")

classifier.predict(sentence)

print(sentence)
```

The problem lies in the `_filter_data_point` method of the `DefaultClassifier`.

**Comment by alanakbik** [comment]
@helpmefindaname I've pushed a small fix for the issue. I'll approve now, but can you double beck before you merge?

**Comment by helpmefindaname** [comment]
@alanakbik good catch, I did a small change so we allow both, setting the `span_label_type` immediately (but training on `label_type` if available) and having it set later instead.

**Review by alanakbik — APPROVED** [review]

**Comment by alanakbik** [comment]
Thanks @helpmefindaname!

**Pull request merged**
