### PR TITLE
datasets: add support for version 2.1 of HIPE-2022

### LINKED ISSUE #2734: Add support for HIPE-2022 v2.1
Hi,

a new version 2.1 was recently released for the HIPE-2022 dataset.

Flair currently only supports version 2.0, so it needs to be updated.

Changelog for v2.1 release:

https://github.com/hipe-eval/HIPE-2022-data/releases/tag/v2.1

### PR DESCRIPTION
**Pull request by stefan-it**
Hi,

this PR adds support for latest version 2.1 of HIPE-2022 dataset.

It mainly fixes a label correction in the HIPE-2020 French data (training split), and some adjustments in AJMC, see [release notes](https://github.com/hipe-eval/HIPE-2022-data/releases/tag/v2.1).

Closes #2734

### CODE REVIEW

**Comment by alanakbik** [comment]
@marcelmmm can you review and merge?

**Review by marcelmmm — COMMENTED** [review]
👍

**Comment by stefan-it** [comment]
I think only one additional approval is missing now :)

**Comment by alanakbik** [comment]
:+1:

**Comment by alanakbik** [comment]
Approval added but I think the whole zappr thing is broken :/ merging now!

**Pull request merged**
