### PR TITLE
Replace sklearn by scikit-learn

### PR DESCRIPTION
**Pull request by dilshatu**
Change the sklearn dependency to scikit-learn (as suggested in the description of sklearn)

### CODE REVIEW

**Comment by alanakbik** [comment]
:+1:

**Comment by alanakbik** [comment]
@dilshatu thanks for fixing this! Also please excuse the delayed response!

**Comment by dilshatu** [comment]
Thank you!

**Comment by dilshatu** [comment]
@alanakbik btw could you please advice me on a new release date, so these changes are applied?

**Comment by alanakbik** [comment]
@dilshatu I'm not sure exactly when, but I want to do a release fairly soon since the current install is broken and we've removed a lot of problematic dependencies. In the meantime, you can always install the latest version via 

```console
pip install --upgrade git+https://github.com/zalandoresearch/flair.git 
```
which will contain all the fixes.

**Pull request merged**
